name: CI - Java 8 Maven (File Processor)

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: 'maven'

      - name: Build, Test and Coverage (JaCoCo)
        run: mvn -B -ntp clean verify

      - name: Upload coverage reports (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            target/site/jacoco/**
            target/jacoco.exec
            target/surefire-reports/**
          if-no-files-found: warn

      - name: Upload to Codecov (optional)
        if: ${{ success() }}
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
